# Generated by Django 4.1.4 on 2023-01-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmemodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
