# Generated by Django 4.1.4 on 2023-01-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
