# Generated by Django 4.1.4 on 2023-01-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
